title: publicradio.info
description: >
  publicradio.info is your home for radio news
  and culture gathered from community stations and independent
  producers around the world. All these radio shows and podcasts
  are not-for-profit and ad-free; spread the love by supporting
  your local community radio station!
url: "http://www.publicradio.info"

collections:
- c201509
- c201510
- c201511
- c201512
- c201601
- c201602
- c201603

exclude: ['vendor']
